WebHospital/Controllers/DbControllers/SpecialtyController.cs
using System.Linq;
using System.Web.Mvc;
using WebHospital.Models;

namespace WebHospital.Controllers.DbControllers
{
    public class SpecialtyController : Controller //Работа с данными таблицы "Специализации"
    {
        HospitalDbContext context = new HospitalDbContext(); //Контекст данных, связи между таблицами
        // GET: Specialty
        public ActionResult GetSpecialties() //Все записи 
        {
            return PartialView(context.Specialty);
        }

        [HttpGet]
        public ActionResult EditSpecialty(int? id) //Переход на форму изменения записи
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            var specialty = context.Specialty.Find(id);
            ViewBag.departments = new SelectList(context.Department, "IDDepartment", "NameDepartment");
            if (specialty != null)
            {
                return View(specialty);
            }
            return HttpNotFound();
        }

        [HttpPost]
        public ActionResult EditSpecialty(Specialty specialty) //Внесение изменений записи в базу данных
        {
            context.Entry(specialty).State = System.Data.Entity.EntityState.Modified;
            context.SaveChanges();
            return RedirectToAction("Structure", "Home");
        }

        [HttpGet]
        public ActionResult CreateSpecialty() //Переход на форму добавления новой записи
        {
            ViewBag.departments = new SelectList(context.Department, "IDDepartment", "NameDepartment");
            return View();
        }
        [HttpPost]
        public ActionResult CreateSpecialty(Specialty specialty) //Добавление записи в базу данных
        {
            context.Specialty.Add(specialty);
            context.SaveChanges();
            return RedirectToAction("Structure", "Home");
        }

        [HttpGet]
        public ActionResult DeleteSpecialty(int id) //Удаление данных
        {
            var specialty = context.Specialty.Find(id);
            if (specialty == null)
            {
                return HttpNotFound();
            }
            return View(specialty);
        }

        [HttpPost, ActionName("DeleteSpecialty")]
        public ActionResult DeleteConfirmedSpecialty(int id) //Удаление записи из базы данных
        {
            var specialty = context.Specialty.Find(id);
            if (specialty == null)
            {
                return HttpNotFound();
            }
            int count = EmployeesCount(id);
            if(count != 0)
            {
                ViewBag.Message = "Невозможно удалить специализацию! Возможное решение: 1. Удалить врачей по данной специализации; 2. Поменять специализацию у врачей, которые относятся к данной специализации.";
                return View(specialty);
            }
            context.Specialty.Remove(specialty);
            context.SaveChanges();
            return RedirectToAction("Structure", "Home");
        }

        private int EmployeesCount(int id) //Количество записей в связанной таблице по идентификатору главной таблицы
        {
            int count = 0;
            var specialties = context.Specialty.Find(id);
            IQueryable<Employee> employees = context.Employee;
            employees = employees.Where(s => s.Specialty == specialties.IDSpecialty);
            count = employees.Count();
            return count;
        }
        protected override void Dispose(bool disposing) //Закрытие соединения с контекстом данных
        {
            context.Dispose();
            base.Dispose(disposing);
        }
    }
}

WebHospital/Views/Specialty/CreateSpecialty.cshtml
@model WebHospital.Models.Specialty

<h2>Новая специализация</h2>
@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.NameSpecialty, "Специализация")
    <br />
    <br />
    @Html.EditorFor(model => model.NameSpecialty, new { htmlAttributes = new { @class = "form-control" } })
    @Html.ValidationMessageFor(model => model.NameSpecialty, null, new { @class = "text-danger" })
    <br />
    @Html.LabelFor(model => model.Department, "Отделение")
    <br />
    <br />
    @Html.DropDownListFor(model => model.Department, ViewBag.departments as SelectList, new { @class = "form-control" })
    @Html.ValidationMessageFor(model => model.Department, null, new { @class = "text-danger" })
    <br />
    <input type="submit" class="btn btn-primary" value="Добавить" />
}

WebHospital/Views/Specialty/DeleteSpecialty.cshtml
@model WebHospital.Models.Specialty

<h2>Удаление записи о специализации</h2>
@ViewBag.Message
<dl>
    <dt>Наименование специализации</dt>
    <dd>
        @Html.DisplayFor(model => model.NameSpecialty)
    </dd>
    <dt>Отделение</dt>
    <dd>
        @Html.DisplayFor(model => model.Department1.NameDepartment)
    </dd>
</dl>
@using (Html.BeginForm())
{
    <input type="submit" class="btn btn-primary" value="Удалить" />
}

WebHospital/Views/Specialty/EditSpecialty.cshtml
@model WebHospital.Models.Specialty

<h2>Изменение специализации</h2>
@using (Html.BeginForm("EditSpecialty", "Specialty", FormMethod.Post))
{
    <fieldset>
        @Html.HiddenFor(m => m.IDSpecialty)
        <p>
            @Html.LabelFor(m => m.NameSpecialty, "Наименование специализации")
            <br />
            @Html.EditorFor(m => m.NameSpecialty, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(m => m.NameSpecialty, null, new { @class = "text-danger" })
        </p>
        <p>
            @Html.LabelFor(m => m.Department, "Наименование отделения")
            <br />
            @Html.DropDownListFor(m => m.Department, ViewBag.departments as SelectList, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Department, null, new { @class = "text-danger" })
        </p>
        <p><input type="submit" class="btn btn-primary" value="Сохранить" /></p>
    </fieldset>
}

WebHospital/Views/Specialty/GetSpecialties.cshtml
@model IEnumerable<WebHospital.Models.Specialty>
<p>
    @Html.ActionLink("Добавить специализацию", "CreateSpecialty", "Specialty")
</p>
<h2>Специализации</h2>
<table class="table">
    @foreach (WebHospital.Models.Specialty s in Model)
    {
        <tr>
            <td>@s.NameSpecialty</td>
            <td>@Html.ActionLink("Редактировать", "EditSpecialty", "Specialty", new { id = s.IDSpecialty }, new { @class = "form-control" })</td>
            <td>@Html.ActionLink("Удалить", "DeleteSpecialty", "Specialty", new { id = s.IDSpecialty }, new { @class = "form-control" })</td>
        </tr>
    }
</table>