WebHospital/Controllers/DbControllers/PatientController.cs
using System.Linq;
using System.Web.Mvc;
using WebHospital.Models;


namespace WebHospital.Controllers.DbControllers
{
    public class PatientController : Controller //Работа с данными таблицы "Пациенты"
    {
        HospitalDbContext context = new HospitalDbContext(); //контекст данных

        [HttpGet]
        public ActionResult DetailsPatient(int id) //Форма просмотра данных по определенной записи
        {
            var patient = context.Patient.Find(id);
            if (patient != null)
            {
                return View(patient);
            }
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public ActionResult EditPatient(int? id) //Переход на форму изменения записи
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            var patient = context.Patient.Find(id);
            if (patient != null)
            {
                return View(patient);
            }
            return HttpNotFound();
        }

        [HttpPost]
        public ActionResult EditPatient(Patient patient) //Внесение изменений записи в базу данных
        {
            context.Entry(patient).State = System.Data.Entity.EntityState.Modified;
            context.SaveChanges();
            return RedirectToAction("Patients", "Home");
        }

        [HttpGet]
        public ActionResult CreatePatient() //Переход на форму добавления новой записи
        {
            return View();
        }
        [HttpPost]
        public ActionResult CreatePatient(Patient patient) //Добавление записи в базу данных
        {
            context.Patient.Add(patient);
            context.SaveChanges();
            return RedirectToAction("Patients", "Home");
        }


        [HttpGet]
        public ActionResult DeletePatient(int id) //Переход на форму удаления записи
        {
            var patient = context.Patient.Find(id);
            if (patient == null)
            {
                return HttpNotFound();
            }
            return View(patient);
        }

        [HttpPost, ActionName("DeletePatient")]
        public ActionResult DeleteConfirmedPatient(int id) //Удаление записи из базы данных
        {
            var patient = context.Patient.Find(id);
            if (patient == null)
            {
                return HttpNotFound();
            }
            int count = PatientsCount(id);
            if(count != 0)
            {
                ViewBag.Message = "Невозможно удалить пациента! Возможное решение: 1. Удалить запись к врачу от данного пациента; 2. Изменить пациента в записи к врачу.";
                return View(patient);
            }
            context.Patient.Remove(patient);
            context.SaveChanges();
            return RedirectToAction("Patients", "Home");
        }

        private int PatientsCount(int id) //Количество записей в связанной таблице по идентификатору главной таблицы
        {
            int count = 0;
            var patients = context.Patient.Find(id);
            IQueryable<Reception> receptions = context.Reception;
            receptions = receptions.Where(s => s.Patient == patients.IDPatient);
            count = receptions.Count();
            return count;
        }

        protected override void Dispose(bool disposing) //Закрытие соединения с контекстом данных
        {
            context.Dispose();
            base.Dispose(disposing);
        }
    }
}

WebHospital/Views/Patient/CreatePatient.cshtml
@model WebHospital.Models.Patient

<h2>Новый пациент</h2>
@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.FIOPatient, "ФИО пациента")
    <br />
    <br />
    @Html.EditorFor(model => model.FIOPatient, new { htmlAttributes = new { @class = "form-control" } })
    @Html.ValidationMessageFor(model => model.FIOPatient, null, new { @class = "text-danger" })
    <br />
    @Html.LabelFor(model => model.Policy, "Полис ОМС")
    <br />
    <br />
    @Html.EditorFor(model => model.Policy, new { htmlAttributes = new { @class = "form-control" } })
    @Html.ValidationMessageFor(model => model.Policy, null, new { @class = "text-danger" })
    <br />
    @Html.LabelFor(model => model.DateOfBirth, "Дата рождения")
    <br />
    <br />
    @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
    @Html.ValidationMessageFor(model => model.DateOfBirth, null, new { @class = "text-danger" })
    <br />
    @Html.LabelFor(model => model.Address, "Адрес")
    <br />
    <br />
    @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
    @Html.ValidationMessageFor(model => model.Address, null, new { @class = "text-danger" })
    <br />
    @Html.LabelFor(model => model.CardNumber, "Номер медицинской карты")
    <br />
    <br />
    @Html.EditorFor(model => model.CardNumber, new { htmlAttributes = new { @class = "form-control" } })
    @Html.ValidationMessageFor(model => model.CardNumber, null, new { @class = "text-danger" })
    <br />
    <input type="submit" class="btn btn-primary" value="Добавить" />
}

WebHospital/Views/Patient/DeletePatient.cshtml
@model WebHospital.Models.Patient

<h2>Удаление пациента</h2>
@ViewBag.Message
<dl>
    <dt>ФИО пациента</dt>
    <dd>
        @Html.DisplayFor(model => model.FIOPatient)
    </dd>
    <dt>Полис ОМС</dt>
    <dd>
        @Html.DisplayFor(model => model.Policy)
    </dd>
    <dt>Дата рождения</dt>
    <dd>
        @Html.DisplayFor(model => model.DateOfBirth)
    </dd>
    <dt>Адрес</dt>
    <dd>
        @Html.DisplayFor(model => model.Address)
    </dd>
    <dt>Номер карты</dt>
    <dd>
        @Html.DisplayFor(model => model.CardNumber)
    </dd>
</dl>
@using (Html.BeginForm())
{
    <input type="submit" class="btn btn-primary" value="Удалить" />
}

WebHospital/Views/Patient/DetailsPatient.cshtml
@model WebHospital.Models.Patient
    
<h2>Информация о пациенте</h2>
<dl>
    <dt>ФИО пациента</dt>
    <dd>
        @Html.DisplayFor(model => model.FIOPatient)
    </dd>
    <dt>Полис ОМС</dt>
    <dd>
        @Html.DisplayFor(model => model.Policy)
    </dd>
    <dt>Дата рождения</dt>
    <dd>
        @Html.DisplayFor(model => model.DateOfBirth)
    </dd>
    <dt>Адрес</dt>
    <dd>
        @Html.DisplayFor(model => model.Address)
    </dd>
    <dt>Номер карты</dt>
    <dd>
        @Html.DisplayFor(model => model.CardNumber)
    </dd>
</dl>

WebHospital/Views/Patient/EditPatient.cshtml
@model WebHospital.Models.Patient

<h2>Изменение данных о пациенте</h2>
@using (Html.BeginForm("EditPatient", "Patient", FormMethod.Post))
{
    <fieldset>
        @Html.HiddenFor(m => m.IDPatient)
        <p>
            @Html.LabelFor(m => m.FIOPatient, "ФИО пациента")
            <br />
            @Html.EditorFor(m => m.FIOPatient, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(m=>m.FIOPatient, null, new { @class = "text-danger" })
        </p>
        <p>
            @Html.LabelFor(m => m.Policy, "Полис ОМС")
            <br />
            @Html.EditorFor(m => m.Policy, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(m => m.Policy, null, new { @class = "text-danger" })
        </p>
        <p>
            @Html.LabelFor(m => m.DateOfBirth, "Дата рождения")
            <br />
            @Html.EditorFor(m => m.DateOfBirth, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(m => m.DateOfBirth, null, new { @class = "text-danger" })
        </p>
        <p>
            @Html.LabelFor(m => m.Address, "Адрес")
            <br />
            @Html.EditorFor(m => m.Address, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(m => m.Address, null, new { @class = "text-danger" })
        </p>
        <p>
            @Html.LabelFor(m => m.CardNumber, "Номер карты")
            <br />
            @Html.EditorFor(m => m.CardNumber, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(m => m.CardNumber, null, new { @class = "text-danger" })
        </p>
        <p><input type="submit" class="btn btn-primary" value="Сохранить" /></p>
    </fieldset>
}